#          YAML Reference Guide: https://www.appveyor.com/docs/appveyor-yml/
# Environmental Variables Guide: https://www.appveyor.com/docs/environment-variables/
#                YAML Validator: https://ci.appveyor.com/tools/validate-yaml

# Disable automatic builds
# Without this, the following error shows up:
# "Specify a project or solution file. The directory does not contain a project or solution file."
build: "off"

# Version number
version: 1.0.0.{build}

# Ignore testing a commit if only the README.md file changed
# Or if various strings are found in the commit message: updated readme, update readme, update docs, update version, update appveyor
skip_commits:
  files:
    - README.md
  message: /updated readme.*|update readme.*s|update docs.*|update version.*|update appveyor.*/

# There's no need to alter the build number for a Pull Request (PR) since they don't modify anything
pull_requests:
  do_not_increment_build_number: true

clone_folder: c:\projects\dRemoveFeature

# PowerShell Gallery API key for publishing an update to the module
# The "secure:" value is the Appveyor encryption of the key
# Encrypting Variables http://wahlnetwork.com/2016/07/19/encrypting-environmental-variables-with-appveyor/
# GitHub token https://www.appveyor.com/docs/how-to/git-push/
environment:
  NuGetApiKey:
    secure: 8zTIgzkh0lIeJ+PZRLSS047LFbQqLbbm2YDdqwgTs4ctfGKtZAKQNDyEtn2geNtq
  GitHubKey:
    secure: BTbC1Dgv/DE7g/n+/emm4FiSiRTjsRYnsqRUiF2NEhuwHvKkS35zCRsFm27g8OR4
  CODECOV_TOKEN:
    secure: VfWRr0lp4/nf9XMtKdNd69TKPTrDq4XpXN/1WLjIkBMzEiRlBfRhS1Xyu1fGV77H


# Install NuGet to interact with the PowerShell Gallery 
install:
  - git clone https://github.com/PowerShell/DscResource.Tests
  - ps: Import-Module -Name "$env:APPVEYOR_BUILD_FOLDER\DscResource.Tests\AppVeyor.psm1"
  - ps: Invoke-AppveyorInstallTask
  - ps: . .\tests\install.ps1

    

# Invoke Pester to run all of the unit tests, then save the results into XML in order to populate the AppVeyor tests section
# If any of the tests fail, consider the pipeline failed
# git commands: https://www.appveyor.com/docs/how-to/git-push/
# Additional Code Coverage Examples
# https://info.sapien.com/index.php/scripting/scripting-modules/testing-pester-code-coverage
test_script:
  - ps: | 
      $res = Invoke-Pester -Path ".\tests\unit" -OutputFormat NUnitXml -OutputFile .\tests\results\TestsResults.xml -PassThru -CodeCoverage .\tests\unit\something.ps1
      (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\tests\results\TestsResults.xml))
      if ($res.FailedCount -gt 0) { throw "$($res.FailedCount) tests failed."}
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:GitHubKey):x-oauth-basic@github.com`n"
  - git config --global user.email "dcuomo@outlook.com"
  - git config --global user.name "Dan Cuomo"
  - git config --global core.autocrlf false
  - git config --global core.safecrlf false
  - ps: . .\tests\build.ps1
  - ps: Invoke-RestMethod -Uri https://codecov.io/validate -Body (Get-Content -Raw -LiteralPath .\.codecov.yml) -Method post